server:
  port: 8095
  
spring:
  application:
    name: enterprisehystrix
    
api:
   zuul:
      url: http://apihost:8087    
      
feign:
  hystrix:
    enabled: true    
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery:8761/eureka/
      
ribbon:
  eureka:
    enabled: true
