server:
  port: 9095
  error:
    whitelabel:
      enabled: false

spring:
  application:
    name: ENTERPRISESERVICEUI
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp


zuul:
  retryable: true
  routes:
    enterpriseservice:
      path: /rest/api/security/enterprises/**
      service-id: enterpriseservice
      strip-prefix: false
    
ribbon:
  eager-load:
    enabled: true
  #ReadTimeout: 3000
  #ConnectTimeout: 3000
  MaxAutoRetriesNextServer: 1
  OkToRetryOnAllOperations: true
  retryable: true
  MaxAutoRetries: 0
  eureka:
    enabled: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery:8761/eureka/
  instance:
    prefer-ip-address: true    
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
hystrix:
 command:
  default:
   execution:
    isolation:
     thread:
      timeoutInMilliseconds: 30000
