server:
  port: 8096
  error:
    whitelabel:
      enabled: false

spring:
  application:
    name: enterpriseserviceui
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp


zuul:
  routes:
    enterpriseservice:
      path: /rest/api/security/enterprises/**
      service-id: enterpriseservice
      strip-prefix: false
    
ribbon:
  eager-load:
    enabled: true
  ReadTimeout: 60000
  ConnectTimeout: 60000
  eureka:
    enabled: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://in1-1021997lt:8761/eureka/
