spring:
  application:
    name: enterpriseservice
  main:
    allow-bean-definition-overriding: true  
  datasource:
    url: jdbc:oracle:thin:@//in1-1021997lt:1521/O12CR201
    username: CSMMGRTIP
    password: CSMMGRTIP
    driver-class-name: oracle.jdbc.driver.OracleDriver
    jndi-name: java:comp/env/TEST_ConnectionPool
    tomcat:
      initial-size: 5
      max-wait: 20000
      max-active: 30
      max-idle: 15
      min-idle: 8
      default-auto-commit: true
      
connection:
  jndiName: TEST_ConnectionPool      
    
server:
  port: 8094
  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://in1-1021997lt:8761/eureka/    
      
ribbon:
  eureka:
    enabled: true
