server:
  port: 8084
  
spring:
  application:
    name: mshystrix
    
api:
   zuul:
      url: http://apihost:8087    
      
feign:
  hystrix:
    enabled: true    
    
eureka:
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka/
    instance:
      preferIpAddress: true
      
ribbon:
  eureka:
    enabled: true
