server:
  port: 4000
  error:
    whitelabel:
      enabled: false
      
spring:
  application:
    name: roleserviceui
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
      
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery:8761/eureka/ 
      
zuul:
  routes:
    roleservice:
      path: /allRoles/json/**
      service-id: roleservice
      strip-prefix: false      
