server:
  port: 5000
  error:
    whitelabel:
      enabled: false
      
spring:
  application:
    name: roleservice
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    url: jdbc:oracle:thin:@//IN1-1021861LT:1521/O12CR201
    username: WWFMGR2018
    password: WWFMGR2018
    driver-class-name: oracle.jdbc.driver.OracleDriver
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://in1-1021997lt:8761/eureka/    
