spring:
  application:
    name: roleservice
  #boot:
    #admin:
      #client:
        #url:
        #- http://localhost:9098  
  main:
    allow-bean-definition-overriding: true  
  datasource:
    url: jdbc:oracle:thin:@//dbhost:1521/O12CR201
    username: CSMMGRTIP
    password: CSMMGRTIP
    driver-class-name: oracle.jdbc.driver.OracleDriver    
    
server:
  port: 5000
  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery:8761/eureka/
    instance:
      hostname: plhost
      instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}} 
      #preferIpAddress: true
      
ribbon:
  eureka:
    enabled: true
