server:
  port: 8087
  error:
    whitelabel:
      enabled: false

spring:
  application:
    name: zuulproxygateway
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
      


zuul:
  routes:
    customerservice:
      path: /rest/api/customers/**
      service-id: customerservice
      strip-prefix: false

    customerservice1:
      path: /nonrest/api/customers/**
      service-id: customerservice
      strip-prefix: false

    catalog:
      path: /api/catalog/**
      service-id: catalog
      strip-prefix: false

    order:
      path: /api/orders/**
      service-id: order
      strip-prefix: false

    platformframework:
      path: /rest/api/platform/**
      service-id: platformframework
      strip-prefix: false

    hystrixframework:
      path: /api/hystrix/**
      service-id: mshystrix
      strip-prefix: false
      
    roleservicehystrix:
      path: /api/rolehystrix/**
      service-id: roleserviceui
      strip-prefix: false
      
    roleserviceui:
      path: /roleserviceui/**
      service-id: roleserviceui
      strip-prefix: false
      
    roleservice:
      path: /allRoles/json/**
      service-id: roleservice
      strip-prefix: false
      
    customerui:
      path: /customerui/**
      service-id: customerui
      strip-prefix: false  

    enterpriseserviceui:
      path: /enterpriseserviceui/**
      service-id: enterpriseserviceui
      strip-prefix: false           
      
    enterpriseservice:
      path: /rest/api/security/enterprises/**
      service-id: enterpriseservice
      strip-prefix: false  
      
    enterprisehystrix:
      path: /api/enterprise/hystrix/**
      service-id: enterprisehystrix
      strip-prefix: false
      
  ignored-services:
  - '*'
  ignored-headers:
  - Access-Control-Allow-Credentials, Access-Control-Allow-Origin
  
 
ribbon:
  eager-load:
    enabled: true
  ReadTimeout: 60000
  ConnectTimeout: 60000
  #eureka:
    #enabled: false
    
eureka:
  instance:
    hostname: plhost
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka/    
    fetch-registry: true
    register-with-eureka: true
